### ISSUE TITLE
java.lang.SecurityException: Can't read cryptographic policy directory: unlimited

### ISSUE THREAD

**Issue by ambarus** [aws/aws-greengrass-core-sdk-java#5]
Hello,

I'm trying to run the HelloWorld java8 lambda function. I could deploy the group on my board.
I copied java binary as java8 in /usr/bin  as it is suggested in readme.
# java8 --version
openjdk 13.0.2 2020-01-14
OpenJDK Runtime Environment (build 13.0.2+13)
OpenJDK Server VM (build 13.0.2+13, mixed mode)

The lambda function is not running on the core device, I'm getting the following error in  /greengrass/ggc/var/log/user/eu-central-1/xyzxzy/gg-wh-java8-2.log:

[2020-04-22T08:23:31.459Z][ERROR]-Exception in thread "main" java.lang.ExceptionInInitializerError
[2020-04-22T08:23:31.473Z][ERROR]-      at java.base/javax.crypto.Cipher.getInstance(Unknown Source)
[2020-04-22T08:23:31.49Z][ERROR]-       at java.base/sun.security.ssl.SSLCipher.isTransformationAvailable(Unknown Source)
[2020-04-22T08:23:31.496Z][ERROR]-      at java.base/sun.security.ssl.SSLCipher.<init>(Unknown Source)
[2020-04-22T08:23:31.497Z][ERROR]-      at java.base/sun.security.ssl.SSLCipher.<clinit>(Unknown Source)
[2020-04-22T08:23:31.498Z][ERROR]-      at java.base/sun.security.ssl.CipherSuite.<clinit>(Unknown Source)
[2020-04-22T08:23:31.499Z][ERROR]-      at java.base/sun.security.ssl.SSLContextImpl.getApplicableSupportedCipherSuites(Unknown Source)
[2020-04-22T08:23:31.501Z][ERROR]-      at java.base/sun.security.ssl.SSLContextImpl$AbstractTLSContext.<clinit>(Unknown Source)
[2020-04-22T08:23:31.502Z][ERROR]-      at java.base/java.lang.Class.forName0(Native Method)
[2020-04-22T08:23:31.506Z][ERROR]-      at java.base/java.lang.Class.forName(Unknown Source)
[2020-04-22T08:23:31.507Z][ERROR]-      at java.base/java.security.Provider$Service.getImplClass(Unknown Source)
[2020-04-22T08:23:31.509Z][ERROR]-      at java.base/java.security.Provider$Service.newInstance(Unknown Source)
[2020-04-22T08:23:31.526Z][ERROR]-      at java.base/sun.security.jca.GetInstance.getInstance(Unknown Source)
[2020-04-22T08:23:31.527Z][ERROR]-      at java.base/sun.security.jca.GetInstance.getInstance(Unknown Source)
[2020-04-22T08:23:31.528Z][ERROR]-      at java.base/javax.net.ssl.SSLContext.getInstance(Unknown Source)
[2020-04-22T08:23:31.529Z][ERROR]-      at org.apache.http.ssl.SSLContexts.createDefault(SSLContexts.java:51)
[2020-04-22T08:23:31.531Z][ERROR]-      at org.apache.http.impl.client.HttpClientBuilder.build(HttpClientBuilder.java:964)
[2020-04-22T08:23:31.532Z][ERROR]-      at org.apache.http.impl.client.HttpClients.createDefault(HttpClients.java:56)
[2020-04-22T08:23:31.536Z][ERROR]-      at com.amazonaws.greengrass.ipcsdk.DefaultIPCClient.<init>(DefaultIPCClient.java:126)
[2020-04-22T08:23:31.537Z][ERROR]-      at com.amazonaws.greengrass.runtime.LambdaRuntime.<init>(LambdaRuntime.java:70)
[2020-04-22T08:23:31.538Z][ERROR]-      at com.amazonaws.greengrass.runtime.LambdaRuntime.main(LambdaRuntime.java:300)
[2020-04-22T08:23:31.548Z][ERROR]-Caused by: java.lang.SecurityException: Can not initialize cryptographic mechanism
[2020-04-22T08:23:31.556Z][ERROR]-      at java.base/javax.crypto.JceSecurity.<clinit>(Unknown Source)
[2020-04-22T08:23:31.557Z][ERROR]-      ... 20 more
[2020-04-22T08:23:31.56Z][ERROR]-Caused by: java.lang.SecurityException: Can't read cryptographic policy directory: unlimited
[2020-04-22T08:23:31.564Z][ERROR]-      at java.base/javax.crypto.JceSecurity.setupJurisdictionPolicies(Unknown Source)
[2020-04-22T08:23:31.565Z][ERROR]-      at java.base/javax.crypto.JceSecurity$1.run(Unknown Source)
[2020-04-22T08:23:31.57Z][ERROR]-       at java.base/javax.crypto.JceSecurity$1.run(Unknown Source)
[2020-04-22T08:23:31.571Z][ERROR]-      at java.base/java.security.AccessController.doPrivileged(Unknown Source)
[2020-04-22T08:23:31.574Z][ERROR]-      ... 21 more

**Comment by ambarus** [comment]
Hi. I made it work. It was an openjdk packaging problem. The issue was similar to what is described at https://github.com/docker-library/openjdk/issues/101. Please close this ticket. Cheers.
