### ISSUE TITLE
Auto detection of device in same network

### ISSUE THREAD

**Issue by RajKumarUpadhyay** [aws/aws-greengrass-core-sdk-java#8]
Hi,

The auto-detection feature of the Greengrass group is not working for those devices which is in the same network. I think this should at least detect those devices which are in the same network rather than provide the device IP address manually in core connectivity.

Problem: 2

Secondly using the Greengrass SDK I'm not able to attach more than one device in the  Greengrass group. When I'm trying to attach a new device, it overrides the existing device. This should be fixed in SDK.

Problem: 3

Using Greengrass SDK not able to create a stream manager client. Getting below error, I search on the support page but couldn't able to find anything related to this issue.

com.amazonaws.greengrass.streammanager.client.StreamManagerClientImpl: Connect failed. Status: UnsupportedProtocolVersioncom.amazonaws.greengrass.streammanager.client.exception.ConnectException: Connect failed
[2020-11-05T14:19:28.584Z][ERROR]-	at com.amazonaws.greengrass.streammanager.client.StreamManagerClientImpl.connect(StreamManagerClientImpl.java:173)
[2020-11-05T14:19:28.584Z][ERROR]-	at com.amazonaws.greengrass.streammanager.client.StreamManagerClientImpl.<init>(StreamManagerClientImpl.java:91)
[2020-11-05T14:19:28.584Z][ERROR]-	at com.amazonaws.greengrass.streammanager.client.StreamManagerClientFactory.build(StreamManagerClientFactory.java:49)

I hope the team will address my concern about the stability of the Greengrass service.

thanks

regards,
raj

**Comment by MikeDombo** [comment]
IP auto-detection is a feature which must be enabled. Have you enabled the feature? Please see: https://docs.aws.amazon.com/greengrass/latest/developerguide/gg-core.html#ip-auto-detect

The Greengrass SDK which is provided in this GitHub repository is not used for controlling Greengrass Groups. For that you should use the Greengrass Console or use the AWS SDK. See: https://docs.aws.amazon.com/greengrass/latest/apireference/createdevicedefinitionversion-post.html

The stream manager error shows an `UnsupportedProtocolVersion` this means that the version of the stream manager SDK and the version of stream manager running in Greengrass are not aligned. Please use the version of the SDK which is appropriate for the version of Greengrass. Consult the compatibility table here:  https://github.com/aws/aws-greengrass-core-sdk-java#compatibility

**Comment by RajKumarUpadhyay** [comment]
Hi Mike,

Regarding UnsupportedProtocolVersion the Stream Manager protocol version in greengrass core is 1.1.0. Below you could see this:

[2020-11-06T09:46:53.628Z][ERROR]- (nioEventLoopGroup-3-1) com.amazonaws.iot.greengrass.streammanager.server.protocol.ConnectHandler: Protocol version not supported. RequestId: 8e00fdf1-2a6c-4abe-ad63-53d974cbadf0, ProtocolVersion 1.1.0

and AWS IoT Greengrass SDK is latest one which I download from here https://github.com/aws/aws-greengrass-core-sdk-java

but unfortunately still I'm getting same error.

[2020-11-06T09:46:53.724Z][ERROR]-com.amazonaws.greengrass.streammanager.client.StreamManagerClientImpl: Connect failed. Status: UnsupportedProtocolVersioncom.amazonaws.greengrass.streammanager.client.exception.ConnectException: Connect failed
[2020-11-06T09:46:53.724Z][ERROR]-	at com.amazonaws.greengrass.streammanager.client.StreamManagerClientImpl.connect(StreamManagerClientImpl.java:173)
[2020-11-06T09:46:53.724Z][ERROR]-	at com.amazonaws.greengrass.streammanager.client.StreamManagerClientImpl.<init>(StreamManagerClientImpl.java:91)
[2020-11-06T09:46:53.724Z][ERROR]-	at com.amazonaws.greengrass.streammanager.client.StreamManagerClientFactory.build(StreamManagerClientFactory.java:49)

Could you suggest what else I have need to look into it. 

thanks!

**Comment by RajKumarUpadhyay** [comment]
> Hi Mike,
> 
> Regarding UnsupportedProtocolVersion the Stream Manager protocol version in greengrass core is 1.10.0. Below you could see this:
> 
> [2020-11-06T09:46:53.628Z][ERROR]- (nioEventLoopGroup-3-1) com.amazonaws.iot.greengrass.streammanager.server.protocol.ConnectHandler: Protocol version not supported. RequestId: 8e00fdf1-2a6c-4abe-ad63-53d974cbadf0, ProtocolVersion 1.1.0
> 
> and AWS IoT Greengrass SDK is latest one which I download from here https://github.com/aws/aws-greengrass-core-sdk-java
> 
> but unfortunately still I'm getting same error.
> 
> [2020-11-06T09:46:53.724Z][ERROR]-com.amazonaws.greengrass.streammanager.client.StreamManagerClientImpl: Connect failed. Status: UnsupportedProtocolVersioncom.amazonaws.greengrass.streammanager.client.exception.ConnectException: Connect failed
> [2020-11-06T09:46:53.724Z][ERROR]- at com.amazonaws.greengrass.streammanager.client.StreamManagerClientImpl.connect(StreamManagerClientImpl.java:173)
> [2020-11-06T09:46:53.724Z][ERROR]- at com.amazonaws.greengrass.streammanager.client.StreamManagerClientImpl.(StreamManagerClientImpl.java:91)
> [2020-11-06T09:46:53.724Z][ERROR]- at com.amazonaws.greengrass.streammanager.client.StreamManagerClientFactory.build(StreamManagerClientFactory.java:49)
> 
> Could you suggest what else I have need to look into it.
> 
> thanks!

**Comment by RajKumarUpadhyay** [comment]
Thanks, Mike for your input.
